### ISSUE TITLE
見た目関連

### ISSUE THREAD

**Issue by Semi11** [ilovejikkenjisshu/ILJJ_Mk-XV#15]
### 見た目関連の問題まとめ
随時追加
- [x] 進行方向を示す矢印の画像
- [ ] Canvas 上 Object の位置調整
- [x] ダイスロール時のアニメーションエフェクト
- [x] Camera調整（必要部分又は全体が映るように）
- [x] Player重なってるときの処理
- [x] Player移動アニメーション
- [x] マスの種類ごとの見た目の変更
- [ ] ゲーム終了処理雑すぎ

**Comment by GarAcT** [comment]
今日もチラッと言ったけど、矢印は画像ではなく円錐とかでもよかでは（Asset減らせるので）

**Comment by proelbtn** [comment]
見た目本気でこだわらないならそれでもいいけど、そこまでprimitiveなobjectだけで構成するの？（まぁどちらでもいいとは思います）

**Comment by GarAcT** [comment]
ダイスのモデル自体がなくなったのでタイトル画面の文字の奴はどうでもよくなったけど、Canvas上のオブジェクトのアンカーとかちょっと見直さないとディスプレイサイズによっては変なことになりそう

**Comment by GarAcT** [comment]
デカくしたら見づらかった
[例](https://github.com/ilovejikkenjisshu/ILJJ_Mk-XV/issues/19#issuecomment-584479184)

**Comment by GarAcT** [comment]
ステージがデカくなってカメラに入りきらなくなってるが、ゲームフローが完成したらそれに合わせて制御する感じにする？

**Comment by Semi11** [comment]
カメラの視点はプレイヤー中心になるんじゃね，一応プレイヤーの周辺しか見えないって設定なわけだし（そこまで実装できるかは知らんが）

**Comment by GarAcT** [comment]
プレイヤーの移動がアニメーションしてくれるなら、カメラ側はプレイヤーにフォーカスしてるだけでよさそう

**Comment by fouryon** [comment]
![コメント 2020-02-12 113329](https://user-images.githubusercontent.com/40783451/74298160-49f87000-4d8c-11ea-86df-d43fe11d706a.png)

とりあえずこれで指してる方向くらいわかるとは思いますがどうしますか

**Comment by Semi11** [comment]
三角形もっと小さくて良きだと思う（マスの配置するのに重ならないようにするのめんどいため）

**Comment by GarAcT** [comment]
色を変えるなどしてみれば

**Comment by fouryon** [comment]
おけ
あと矢印マスプレイヤーはプレハブのインスタンスにしちゃって大丈夫ですか

**Comment by GarAcT** [comment]
？

**Comment by fouryon** [comment]
今配置してあるやつは多分全部複製で作ってあって変更を一個一個反映させなきゃいけないけどプレハブと紐づければプレハブの変更だけで全部変えられるので

**Comment by GarAcT** [comment]
いやいまPrefabから作ってるはずだが…？

**Comment by fouryon** [comment]
マ？

**Comment by GarAcT** [comment]
ゲーム開始時にPrefabをもとにCloneしているはずなのですでにあるPrefabをいじればいいはず

**Comment by fouryon** [comment]
あーそっか実行すれば反映されるんか
うんこでしたすみません

**Comment by GarAcT** [comment]
（ @Semi11  ともうちょっと緊密に連携したほうがいいと思います）

**Comment by Semi11** [comment]
Canvas上のオブジェクト，今のとこ余程変なアスペクト比にしないと変にならないけど，どういうのを想定してるの？ @GarAcT

**Comment by GarAcT** [comment]
いやまあどういうのを想定しているかといえばよほど変なサイズを想定しているので…

**Comment by Semi11** [comment]
アンカー変えるやつもあらゆるサイズに対応できるような代物じゃなさそうだし，わざわざ変なサイズ想定する必要ある？

**Comment by GarAcT** [comment]
これに関しては気になった程度のことでしかないのでやらんでもいい

**Comment by Semi11** [comment]
じゃあなんか神がかった解決策くるまで放置で
ダイスアニメーションはなんか数字がランダムに出るとかでいいの？

**Comment by GarAcT** [comment]
そこはそっちで考えてくれ

**Comment by fouryon** [comment]
![コメント 2020-02-13 130458](https://user-images.githubusercontent.com/40783451/74400613-c6a94e00-4e61-11ea-92b5-1bedd764d15d.png)
小さくして色を変えました

**Comment by GarAcT** [comment]
オッケーなのでプルリク開けといて

**Comment by Semi11** [comment]
これカメラに座標渡すうんぬんてやるとまたstageManagerの仕事増えるな

**Comment by GarAcT** [comment]
プレイヤーごとに色変えてもよくね？
赤・青・黄色・緑みたいな

**Comment by chuyii** [comment]
ひとまずプレイヤーの色とアニメーションを改良します

**Comment by GarAcT** [comment]
Playerが重なってるやつ、Playerごとに色さえ変えれば、ほんの微小なOffsetをそれぞれ固有の方向に加算してあげれば、勝手にカラフルなボールっぽく見える説

**Comment by chuyii** [comment]
天才だわ。終わったらそれもすぐやる

**Comment by GarAcT** [comment]
誰がどのペアなのかわからん問題
