### ISSUE TITLE
サイコロを振るやつ

### ISSUE THREAD

**Issue by GarAcT** [ilovejikkenjisshu/ILJJ_Mk-XV#18]
## 概要
GameManagerから呼ばれるコルーチン

### 動作
1. ダイアログを表示
1. ユーザーの入力を待つ（「サイコロを振る」ボタンみたいな）
1. ランダムな数値を選ぶ
1. 数値をダイアログに表示（数秒待つでもユーザーにOKボタンを押させるでも可）
1. GameManagerまで値を返す

**Comment by GarAcT** [comment]
各プレイヤーのターン毎に呼ばれる処理だけど、これ自体はプレイヤーとは結び付いてないからそっちの実装を待たずに手を付けられるはず

**Comment by chuyii** [comment]
命名センスがないのでいいのがあったら教えてください。
ひとまず
・ダイアログだす
・ボタン押されるまでまつ
・押されたら数字を表示して1秒後に消える
・出た目を返す
を実装しました。
アニメーションは保留。
（ボタン押されるまでアニメーションするってなるとwaitforなんちゃらをもう一個つくったほうがいいのかね？）
