### ISSUE TITLE
もうちょっと広いステージ

### ISSUE THREAD

**Issue by GarAcT** [ilovejikkenjisshu/ILJJ_Mk-XV#19]
今のSimpleStageSceneにあるマス、いくらなんでも少なすぎるんでもうちょっと広いのを誰か作っといて 👍  （SimpleStageSceneを直接書き換えて良い）

**Comment by Semi11** [comment]
マスの命名ってアルファベット順じゃなきゃ駄目？
あと何マスくらい増やす？

**Comment by GarAcT** [comment]
マスの命名はどうでもよい（アルファベットはどうせ足りなくなるし）
マス数はとりあえず20ぐらいあれば良いかなという感じ
どちらかというと数よりもいろんなケースを作って欲しい

**Comment by Semi11** [comment]
ケースっていうと分岐数と並べ方？

**Comment by GarAcT** [comment]
そういうこと

**Comment by Semi11** [comment]
![2020-02-11_13h56_37](https://user-images.githubusercontent.com/20125266/74212184-5f12c780-4cd6-11ea-9473-eef2cf10e7c5.png)
どうすか

**Comment by GarAcT** [comment]
双方向の接続も作れたと思ったけど、適当に散りばめられない？

**Comment by Semi11** [comment]
![2020-02-11_14h03_20](https://user-images.githubusercontent.com/20125266/74212393-49ea6880-4cd7-11ea-8f69-13dd7569b1ea.png)
あえて作ってなかったわ
こんなん？

**Comment by GarAcT** [comment]
おっけPR出しといて
（めちゃくちゃ見づらいのは見た目の問題だな…）

**Comment by Semi11** [comment]
矢印が正三角形なのが敗因

**Comment by GarAcT** [comment]
距離に応じて引き延ばしたりできると良いかも…
