### ISSUE TITLE
players, squaresのデータ構造の持ち方

### ISSUE THREAD

**Issue by proelbtn** [ilovejikkenjisshu/ILJJ_Mk-XV#26]
現状はprimitiveなarrayを使っているけどCollectionsのArrayだったりListを使いたくないですか？（.Selectとか出来なくて泣いちゃう）

**Comment by Semi11** [comment]
あるならそっちのが良さそう（C＃わからない）

**Comment by GarAcT** [comment]
こっちももともとそうなってたからそうしただけなんでその方がいいすね

**Comment by proelbtn** [comment]
じゃあ気が向いたら（その2つのPRがマージされたら）スッと変更加えます
