### ISSUE TITLE
Playerを歩かせたい

### ISSUE THREAD

**Issue by chuyii** [ilovejikkenjisshu/ILJJ_Mk-XV#28]
サイコロの出た目に応じてplayerを進める方法だけど
- 一歩ずつ選ばせる（実装は楽そう）
- 到着先を選ばせる（分岐とかがあって複数のルートからたどり着ける時にどっちのルートを通るかってのが面倒そう。マスの上を通らせなくていいなら直線で移動させればいいのだけど。）

の2つを考えてるんだけどどうだろうか。

**Comment by GarAcT** [comment]
分岐マスの濃度によるよなぁ、という気が
分岐マスがあんまり無いのを想定するなら分岐のたびに選ばせるのが良いと思うけど、ほとんどが分岐マスみたいなのを想定すると一回で選べた方が良いよね

**Comment by GarAcT** [comment]
到着先を選ばせるとすると、どうせ構造的には一マスずつ探索していかなきゃいけないので、その時の探索ルートを残しておけばよさそうだけど…（データ構造がめんどくさそう）

**Comment by chuyii** [comment]
到着先を選ばせるほうにしよう。
その場合は移動アニメーションは

- マス無視の一直線
- 適当なルートを選んで各マスを経由

だったら後者のほうがいいよね。

**Comment by GarAcT** [comment]
まあ後者の方がすごろくっぽいと思います

**Comment by chuyii** [comment]
selectDest(player, dicenum)
- player.Posからnextをたどって進める範囲までの多分木を作る（parentを持つようにしておく）
- 葉ノードのマスは「行き先候補マス」として保持しておく（リストとか？）
- 行き先候補マスの色等を変えて選択できるようにする
- プレイヤーがマスを選択したら木のparentをrootまでたどりながら「移動アニメーション用スタック」にpush
- 行き先候補マスの色等を戻す
- 移動アニメーション用スタックを返す

movePlayer(player, dicenum)
- selectDest(player, dicenum)を呼んで移動アニメーション用スタックを返してもらう
- スタックからpopしながら一マス移動用のアニメーションを呼ぶ

こんなのでどうでしょう
