### ISSUE TITLE
マスの移動先を示す矢印ニキ

### ISSUE THREAD

**Issue by GarAcT** [ilovejikkenjisshu/ILJJ_Mk-XV#3]
マスの移動先の参照から自動生成してほしい

**Comment by Semi11** [comment]
@GarAcT 
マスのgetNextの実装って僕がやっちゃっていいんですか

**Comment by GarAcT** [comment]
正直要らんくねという気もするが実装に必要ならなんでもやっちゃってくれ
あとでレビューするので

**Comment by GarAcT** [comment]
こっちにやって欲しいことがあったら別途Issueを立ててくれ
