### ISSUE TITLE
マスのイベント

### ISSUE THREAD

**Issue by GarAcT** [ilovejikkenjisshu/ILJJ_Mk-XV#30]
案を募集しています

**Comment by GarAcT** [comment]
イベントを呼ぶ実装は別として、まあある程度適当なイベント内容を考えとかないと…

**Comment by fouryon** [comment]
とりあえず絶対必要なのはペア組むイベントと死ぬイベントだよね

**Comment by GarAcT** [comment]
ペアをどうやって組ませるか…

**Comment by GarAcT** [comment]
これ、あと心中機能さえ実装すれば提出できるんじゃね？

**Comment by Semi11** [comment]
案（楽そうなの）
ペアマス：止まったらダイス降って出目によって（３以上とかで）ペアが組めるか決める（組む相手はランダム）
心中マス：ペア組むまでは通常マス，組んだら出目によって心中

**Comment by GarAcT** [comment]
あー良いんじゃね（適当

**Comment by chuyii** [comment]
よさげ（適当
だとしたら
- Playerに相手をもたせる
- マスにイベントをもたせる

ができればいいのか

**Comment by Semi11** [comment]
あとはプレイヤーの生死かな

**Comment by Semi11** [comment]
心中した時点でゲーム終了でいいか

**Comment by GarAcT** [comment]
最初に心中したペアが勝ち　あとは負け組　さよなら

**Comment by chuyii** [comment]
そうしよ

**Comment by Semi11** [comment]
マスはストラテジーパターンとかでさくっとできそう

**Comment by Semi11** [comment]
@chuyii これと#15どっちやりたい？

**Comment by chuyii** [comment]
#15かな。Player重なってるときの処理はだるそうだけど

**Comment by Semi11** [comment]
おけ
