### ISSUE TITLE
Playerの中身

### ISSUE THREAD

**Issue by GarAcT** [ilovejikkenjisshu/ILJJ_Mk-XV#4]
突っ立ってないで歩けっつってんの

**Comment by GarAcT** [comment]
これ誰かやっといて欲しい…

**Comment by chuyii** [comment]
ひとまず名前(name)といるマス(pos)をprivateで持っておいて、
・SetNameでnameが設定できる
・GetNameでthis.nameを返す
はすぐやる。
初期マス(pos)はStageManagerでSetして、SetPosの中でプレイヤーのtransform.positionを設定する感じでやろうと思う。
プレイヤーはひとまず「指定された次のマスに移動する」ができればいい？

**Comment by GarAcT** [comment]
あー神
強いて言うなら、C#のプロパティが使えるのではないかな、などと…

**Comment by chuyii** [comment]
プロパティすげぇな、使うわ。
これ実装する時どこのブランチから引っ張ってくるのがいいかな

**Comment by GarAcT** [comment]
#21 でPlayerをStageManagerで生成するようにしたんで、一番安全なのはこれがmergeされた後のdevelopから分岐するのだろうけど…（今日一日proelbtnが反応ないのですぐにとはいかなそう）
Player側の変更は入れてないので今のdevelopから分岐して書き始めて #21 がmergeされ次第作業ブランチにdevelopをmergeか、次いで（まだ変更が入るかもしれない）implement-StageManagerから分岐とかかな

**Comment by GarAcT** [comment]
#21 をmergeしたのでdevelopから分岐して大丈夫です 👍
