### ISSUE TITLE
GameManager

### ISSUE THREAD

**Issue by GarAcT** [ilovejikkenjisshu/ILJJ_Mk-XV#9]

**Comment by proelbtn** [comment]
ここ何日かが辛すぎてこっちに手がつく気配が無い。。。

**Comment by GarAcT** [comment]
どうするんすか？無理そうならこっちでやりますが
@proelbtn

**Comment by proelbtn** [comment]
本当ですか（お願いしたい）

**Comment by GarAcT** [comment]
GameManagerの骨組みはできたんで、中身を書いていきましょう
- ゲームが終わるまで
  - プレイヤーごとに
    - サイコロを振って
    - 出た目に応じた行先マスを選ばせて
    - マスに応じたイベントを実行する

**Comment by GarAcT** [comment]
GameManagerについては構造的な変更は今後無いと思うけど、StageManagerの実装（特にPlayer周り）が不足している
